import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'sr/styles/Home.module.scss'
import KystLogo from "../../public/images/kyst-logo.png"
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>K.Y.S.T App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>

        </div>

        <div className={styles.center}>
        <Image src={KystLogo}></Image>
        </div>

        <div className={styles.grid}>
        </div>
      </main>
    </>
  )
}
