import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from 'sr/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>K.Y.S.T App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.description}>

          <div>

          </div>
        </div>

        <div className={styles.center}>
        <h1>K.Y.S.T</h1>
        <p>KEEP YOUR SHIT TOGETHER</p>
        </div>

        <div className={styles.grid}>
        <Link href="/signUpPage">Go to startpage</Link>
        </div>
      </main>
    </>
  )
}
